"t
DDeviceIDLE"IDLE15^ºI¬¯´@A5^ºI¬¯´@QJùæíöùÖ?YJùæíöùÖ?ŠUnknown
£DeviceConv2DBackpropFilter"?gradient_tape/sequential_1/conv2d_7/Conv2D/Conv2DBackpropFilter(1Ãõ(\Õ˜@9Ãõ(\Õ˜@AÃõ(\Õ˜@IÃõ(\Õ˜@QÇì¥÷Û”»?Y|tĞë-ßİ?ŠUnknown
¡DeviceConv2DBackpropInput">gradient_tape/sequential_1/conv2d_7/Conv2D/Conv2DBackpropInput(1®Gáz¬’@9®Gáz¬‚@A®Gáz¬’@I®Gáz¬‚@Q«ÄZJ½´?YÓ’³9@‡á?ŠUnknown
vDevice_FusedConv2D"sequential_1/conv2d_7/Relu(1®Gáz+@9®Gáz+o@A®Gáz+@I®Gáz+o@Q†…õJ:O±?Y„Cƒ'±ã?ŠUnknown
£DeviceConv2DBackpropFilter"?gradient_tape/sequential_1/conv2d_9/Conv2D/Conv2DBackpropFilter(1%•C‰y@9%•C‰i@A%•C‰y@I%•C‰i@Qƒ.b]œ?YøT…Ÿ”ä?ŠUnknown
§DeviceSoftmaxCrossEntropyWithLogits":categorical_crossentropy/softmax_cross_entropy_with_logits(1–C‹lç£x@9–C‹lç£x@A–C‹lç£x@I–C‹lç£x@Q®K‚ØB^›?YUgI¶oå?ŠUnknown
£DeviceConv2DBackpropFilter"?gradient_tape/sequential_1/conv2d_6/Conv2D/Conv2DBackpropFilter(1¬Zdãu@9¬Zdãu@A¬Zdãu@I¬Zdãu@Qñ gÀO˜?Y]ì…¹1æ?ŠUnknown
„DeviceReluGrad",gradient_tape/sequential_1/conv2d_8/ReluGrad(1ü©ñÒM`u@9ü©ñÒM`u@Aü©ñÒM`u@Iü©ñÒM`u@Qm,N&¾—?YÀ]îpïæ?ŠUnknown
„	DeviceReluGrad",gradient_tape/sequential_1/conv2d_6/ReluGrad(1^ºI)t@9^ºI)t@A^ºI)t@I^ºI)t@Qüà$ÿcd–?YÈ„”¢ç?ŠUnknown
£
DeviceConv2DBackpropFilter"?gradient_tape/sequential_1/conv2d_8/Conv2D/Conv2DBackpropFilter(1Ë¡E¶ó¥s@9Ë¡E¶ó¥s@AË¡E¶ó¥s@IË¡E¶ó¥s@Qù7AÓÒ•?Yx=¨*Qè?ŠUnknown
¡DeviceConv2DBackpropInput">gradient_tape/sequential_1/conv2d_9/Conv2D/Conv2DBackpropInput(1fffffds@9fffffdc@Afffffds@Ifffffdc@QV±@Š•?YC…Èzıè?ŠUnknown
gDevice_Send"IteratorGetNext/_1(1Zd;ßr@9Zd;ßr@AZd;ßr@IZd;ßr@QT&Që”?Y6ÌßOçé?ŠUnknown
¡DeviceConv2DBackpropInput">gradient_tape/sequential_1/conv2d_8/Conv2D/Conv2DBackpropInput(1Ï÷Sã¥™q@9Ï÷Sã¥™a@AÏ÷Sã¥™q@IÏ÷Sã¥™a@Q*B,ŠyŒ“?YG.1K:ê?ŠUnknown
„DeviceReluGrad",gradient_tape/sequential_1/conv2d_7/ReluGrad(1{®Gáxq@9{®Gáxq@A{®Gáxq@I{®Gáxq@Q9:†7h“?Y`í½‹Õê?ŠUnknown
vDevice_FusedConv2D"sequential_1/conv2d_9/Relu(1İ$•Ap@9İ$•Ap@Aİ$•Ap@Iİ$•Ap@QÈî\¦Q’?YG Kşeë?ŠUnknown
™DeviceMaxPoolGrad">gradient_tape/sequential_1/max_pooling2d_3/MaxPool/MaxPoolGrad(1D‹lçû¥k@9D‹lçû¥k@AD‹lçû¥k@ID‹lçû¥k@QÍ¯™µ?YNš@¯Ôàë?ŠUnknown
vDevice_FusedConv2D"sequential_1/conv2d_6/Relu(1çû©ñÒõh@9çû©ñÒõh@Açû©ñÒõh@Içû©ñÒõh@Q‡_!'@¹‹?YÌİ¯¹Oì?ŠUnknown
vDevice_FusedConv2D"sequential_1/conv2d_8/Relu(1œÄ °rh@9œÄ °rh@AœÄ °rh@IœÄ °rh@Qñ'—äzºŠ?Yl|o›£ºì?ŠUnknown
{DeviceMaxPool"$sequential_1/max_pooling2d_3/MaxPool(1D‹lçûù^@9D‹lçûù^@AD‹lçûù^@ID‹lçûù^@Qã#Cö3?Y¼|tsÿì?ŠUnknown
„DeviceReluGrad",gradient_tape/sequential_1/conv2d_9/ReluGrad(1mçû©ñ"[@9mçû©ñ"[@Amçû©ñ"[@Imçû©ñ"[@Q‹9ÑÖ$~?Y/«)»;í?ŠUnknown
’DeviceBiasAddGrad"7gradient_tape/sequential_1/conv2d_6/BiasAdd/BiasAddGrad(1{®Gá"[@9{®Gá"[@A{®Gá"[@I{®Gá"[@Q‡æ'¤ú#~?Yüúqƒxí?ŠUnknown
’DeviceBiasAddGrad"7gradient_tape/sequential_1/conv2d_7/BiasAdd/BiasAddGrad(1ôıÔxéÎW@9ôıÔxéÎW@AôıÔxéÎW@IôıÔxéÎW@QK?°qz?Y,‘ğãæ¬í?ŠUnknown
¤DeviceConv2DBackpropFilter"@gradient_tape/sequential_1/conv2d_10/Conv2D/Conv2DBackpropFilter(1\Âõ(V@9\Âõ(F@A\Âõ(V@I\Âõ(F@Qâ¨6º%tx?Y~şd/Ïİí?ŠUnknown
¤DeviceConv2DBackpropFilter"@gradient_tape/sequential_1/conv2d_11/Conv2D/Conv2DBackpropFilter(1\Âõ(V@9\Âõ(F@A\Âõ(V@I\Âõ(F@Qâ¨6º%tx?YĞkÙz·î?ŠUnknown
Device_FusedConv2D"sequential_1/conv2d_10/Relu(1mçû©ñzT@9mçû©ñzD@Amçû©ñzT@Imçû©ñzD@Q˜InÚe¿v?YcHF6<î?ŠUnknown™k=:3ç?
¢DeviceConv2DBackpropInput"?gradient_tape/sequential_1/conv2d_11/Conv2D/Conv2DBackpropInput(1+‡ÙÎ÷S@9+‡ÙÎ÷C@A+‡ÙÎ÷S@I+‡ÙÎ÷C@QÏÖ,]¾-v?Y¢HÃ‘hî?ŠUnknown
™DeviceMaxPoolGrad">gradient_tape/sequential_1/max_pooling2d_4/MaxPool/MaxPoolGrad(1Ûù~j¼tS@9Ûù~j¼tS@AÛù~j¼tS@IÛù~j¼tS@Q·”)œu?YËmÊ“î?ŠUnknown
wDevice_FusedConv2D"sequential_1/conv2d_11/Relu(1åĞ"Ûù&Q@9åĞ"Ûù&Q@AåĞ"Ûù&Q@IåĞ"Ûù&Q@Q{‘us?YuîXLä¹î?ŠUnknown
¢DeviceConv2DBackpropInput"?gradient_tape/sequential_1/conv2d_10/Conv2D/Conv2DBackpropInput(1L7‰A`åP@9L7‰A`å@@AL7‰A`åP@IL7‰A`å@@Q:œ>Är?Y¥&”Élßî?ŠUnknown
’DeviceBiasAddGrad"7gradient_tape/sequential_1/conv2d_8/BiasAdd/BiasAddGrad(1ªñÒMbH@9ªñÒMbH@AªñÒMbH@IªñÒMbH@QíÔí±hºj?YzF2'úî?ŠUnknown
{DeviceMaxPool"$sequential_1/max_pooling2d_4/MaxPool(1Zd;ßOG@9Zd;ßOG@AZd;ßOG@IZd;ßOG@Q)µUgÓ(j?Y/j­Pï?ŠUnknown
’ DeviceBiasAddGrad"7gradient_tape/sequential_1/conv2d_9/BiasAdd/BiasAddGrad(1NbX9F@9NbX9F@ANbX9F@INbX9F@Qæûßì7th?Y+Jš=Ä,ï?ŠUnknown
™!DeviceMaxPoolGrad">gradient_tape/sequential_1/max_pooling2d_5/MaxPool/MaxPoolGrad(1şÔxé&E@9şÔxé&E@AşÔxé&E@IşÔxé&E@Q"ÜG¢¢âg?Y’<à¦Dï?ŠUnknown
¾"Device	Transpose"egradient_tape/sequential_1/conv2d_6/Conv2D/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer(1j¼t“¸>@9j¼t“¸>@Aj¼t“¸>@Ij¼t“¸>@Qö^&#£a?Yf¸_ƒ¶Uï?ŠUnknown
q#DeviceMatMul"sequential_1/dense_2/MatMul(1;ßO—n2@9;ßO—n2@A;ßO—n2@I;ßO—n2@Q„wd}şxT?Y¢jó_ï?ŠUnknown
…$DeviceReluGrad"-gradient_tape/sequential_1/conv2d_11/ReluGrad(1ü©ñÒMb0@9ü©ñÒMb0@Aü©ñÒMb0@Iü©ñÒMb0@QvøS©2R?YìGWiï?ŠUnknown
…%DeviceReluGrad"-gradient_tape/sequential_1/conv2d_10/ReluGrad(19´Èv¾Ÿ*@99´Èv¾Ÿ*@A9´Èv¾Ÿ*@I9´Èv¾Ÿ*@Q¿sæ&S’M?Y;¦ìppï?ŠUnknown
“&DeviceBiasAddGrad"8gradient_tape/sequential_1/conv2d_11/BiasAdd/BiasAddGrad(19´Èv¾Ÿ*@99´Èv¾Ÿ*@A9´Èv¾Ÿ*@I9´Èv¾Ÿ*@Q¿sæ&S’M?YØ_Û€Õwï?ŠUnknown
s'DeviceSoftmax"sequential_1/dense_3/Softmax(1ºI+‡&@9ºI+‡&@AºI+‡&@IºI+‡&@Q¡u%Ò¨I?Y5éë~ï?ŠUnknown
g(Device_Send"IteratorGetNext/_3(1j¼t“&@9j¼t“&@Aj¼t“&@Ij¼t“&@QŞU‡tH?YŠÌñï3„ï?ŠUnknown
\)DeviceArgMax"ArgMax(1{®Gáz$@9{®Gáz$@A{®Gáz$@I{®Gáz$@Q“öÄ§S¿F?YÈ½ÛÄã‰ï?ŠUnknown
^*DeviceArgMax"ArgMax_1(1;ßO—n"@9;ßO—n"@A;ßO—n"@I;ßO—n"@Q„wd}şxD?Yæ{ï?ŠUnknown
+DeviceMatMul"+gradient_tape/sequential_1/dense_2/MatMul_1(1;ßO—n"@9;ßO—n"@A;ßO—n"@I;ßO—n"@Q„wd}şxD?YpD ”ï?ŠUnknown
q,DeviceMatMul"sequential_1/dense_3/MatMul(1;ßO—n"@9;ßO—n"@A;ßO—n"@I;ßO—n"@Q„wd}şxD?Y"É¹ƒ>™ï?ŠUnknown
“-DeviceBiasAddGrad"8gradient_tape/sequential_1/conv2d_10/BiasAdd/BiasAddGrad(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvøS©2B?Y Š.Ëï?ŠUnknown
.DeviceMatMul")gradient_tape/sequential_1/dense_2/MatMul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvøS©2B?YKcØW¢ï?ŠUnknown
/DeviceMatMul")gradient_tape/sequential_1/dense_3/MatMul(1yé&1¬@9yé&1¬@Ayé&1¬@Iyé&1¬@QÎòFQ¨Ø??YüsmíR¦ï?ŠUnknown
š0DeviceResourceApplyGradientDescent".SGD/SGD/update_12/ResourceApplyGradientDescent(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK;?Y»-m¼©ï?ŠUnknown
1DeviceMatMul"+gradient_tape/sequential_1/dense_3/MatMul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK;?Yz•ìì%­ï?ŠUnknown
{2DeviceMaxPool"$sequential_1/max_pooling2d_5/MaxPool(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK;?Y9&¬l°ï?ŠUnknown
š3DeviceResourceApplyGradientDescent".SGD/SGD/update_10/ResourceApplyGradientDescent(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q“öÄ§S¿6?YØ!Wg³ï?ŠUnknown
½4Device	Transpose"dgradient_tape/sequential_1/max_pooling2d_5/MaxPool/MaxPoolGrad-2-TransposeNHWCToNCHW-LayoutOptimizer(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q“öÄ§S¿6?Yw–A?¶ï?ŠUnknown
¥5Device	Transpose"Lsequential_1/max_pooling2d_5/MaxPool-0-2-TransposeNCHWToNHWC-LayoutOptimizer(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q“öÄ§S¿6?Y,¹ï?ŠUnknown
—6DeviceResourceApplyGradientDescent"+SGD/SGD/update/ResourceApplyGradientDescent(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvøS©22?Y•p5]»ï?ŠUnknown
š7DeviceResourceApplyGradientDescent".SGD/SGD/update_14/ResourceApplyGradientDescent(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvøS©22?YÑ_Ö£½ï?ŠUnknown
™8DeviceResourceApplyGradientDescent"-SGD/SGD/update_2/ResourceApplyGradientDescent(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvøS©22?Y“1Š+ê¿ï?ŠUnknown
™9DeviceResourceApplyGradientDescent"-SGD/SGD/update_6/ResourceApplyGradientDescent(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvøS©22?Y’´€0Âï?ŠUnknown
™:DeviceResourceApplyGradientDescent"-SGD/SGD/update_8/ResourceApplyGradientDescent(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvøS©22?Y‘òŞÕvÄï?ŠUnknown
š;DeviceResourceApplyGradientDescent".SGD/SGD/update_13/ResourceApplyGradientDescent(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q/U°QDN+?Y–$º+Æï?ŠUnknown
™<DeviceResourceApplyGradientDescent"-SGD/SGD/update_9/ResourceApplyGradientDescent(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q/U°QDN+?Y›(iàÇï?ŠUnknown
m=DeviceRelu"sequential_1/dense_2/Relu(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q/U°QDN+?Y C®‚•Éï?ŠUnknown
v>DeviceAssignAddVariableOp"AssignAddVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?YÿBJËï?ŠUnknown
x?DeviceAssignAddVariableOp"AssignAddVariableOp_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?Y^ÔmÿÌï?ŠUnknown
X@DeviceCast"Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?Y½œMÂ³Îï?ŠUnknown
gADevice
LogicalAnd"
LogicalAnd(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?Ye-‚hĞï?ŠUnknown
~BDeviceAssignAddVariableOp"SGD/SGD/AssignAddVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?Y{-BÒï?ŠUnknown
™CDeviceResourceApplyGradientDescent"-SGD/SGD/update_1/ResourceApplyGradientDescent(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?YÚõìÒÓï?ŠUnknown
šDDeviceResourceApplyGradientDescent".SGD/SGD/update_11/ResourceApplyGradientDescent(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?Y9¾ÌÁ†Õï?ŠUnknown
šEDeviceResourceApplyGradientDescent".SGD/SGD/update_15/ResourceApplyGradientDescent(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?Y˜†¬;×ï?ŠUnknown
™FDeviceResourceApplyGradientDescent"-SGD/SGD/update_3/ResourceApplyGradientDescent(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?Y÷NŒAğØï?ŠUnknown
™GDeviceResourceApplyGradientDescent"-SGD/SGD/update_4/ResourceApplyGradientDescent(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?YVl¥Úï?ŠUnknown
™HDeviceResourceApplyGradientDescent"-SGD/SGD/update_5/ResourceApplyGradientDescent(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?YµßKÁYÜï?ŠUnknown
™IDeviceResourceApplyGradientDescent"-SGD/SGD/update_7/ResourceApplyGradientDescent(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?Y¨+Şï?ŠUnknown
qJDeviceCast"categorical_crossentropy/Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?YspAÃßï?ŠUnknown
ŒKDeviceCast"8categorical_crossentropy/weighted_loss/num_elements/Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?YÒ8ë xáï?ŠUnknown
„LDeviceDivNoNan",categorical_crossentropy/weighted_loss/value(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?Y1ËÀ,ãï?ŠUnknown
bMDeviceDivNoNan"
div_no_nan(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?YÉª€áäï?ŠUnknown
dNDeviceDivNoNan"div_no_nan_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?Yï‘Š@–æï?ŠUnknown
ODeviceTile";gradient_tape/categorical_crossentropy/weighted_loss/Tile_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?YNZj Kèï?ŠUnknown
PDeviceDivNoNan"Egradient_tape/categorical_crossentropy/weighted_loss/value/div_no_nan(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?Y­"JÀÿéï?ŠUnknown
‘QDeviceBiasAddGrad"6gradient_tape/sequential_1/dense_2/BiasAdd/BiasAddGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?Yë)€´ëï?ŠUnknown
ƒRDeviceReluGrad"+gradient_tape/sequential_1/dense_2/ReluGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?Yk³	@iíï?ŠUnknown
‘SDeviceBiasAddGrad"6gradient_tape/sequential_1/dense_3/BiasAdd/BiasAddGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?YÊ{éÿïï?ŠUnknown
sTDeviceBiasAdd"sequential_1/dense_2/BiasAdd(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q±ô…üıK+?Y)DÉ¿Òğï?ŠUnknown
xUDeviceAssignAddVariableOp"AssignAddVariableOp_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvøS©2"?Yit^êõñï?ŠUnknown
xVDeviceAssignAddVariableOp"AssignAddVariableOp_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvøS©2"?Y©¤óóï?ŠUnknown
xWDeviceAssignAddVariableOp"AssignAddVariableOp_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvøS©2"?YéÔˆ?<ôï?ŠUnknown
ZXDeviceCast"Cast_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvøS©2"?Y)j_õï?ŠUnknown
ZYDeviceCast"Cast_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvøS©2"?Yi5³”‚öï?ŠUnknown
ZZDeviceEqual"Equal(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvøS©2"?Y©eH¿¥÷ï?ŠUnknown
V[DeviceMul"Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvøS©2"?Yé•İéÈøï?ŠUnknown
X\DeviceSum"Sum_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvøS©2"?Y)Ærìùï?ŠUnknown
}]DeviceSum"*categorical_crossentropy/weighted_loss/Sum(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvøS©2"?Yiö?ûï?ŠUnknown
Ÿ^DeviceMul"Lgradient_tape/categorical_crossentropy/softmax_cross_entropy_with_logits/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvøS©2"?Y©&i2üï?ŠUnknown
s_DeviceBiasAdd"sequential_1/dense_3/BiasAdd(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvøS©2"?YéV2”Uıï?ŠUnknown
f`Device_Recv"strided_slice/_12(1¸…ëQ¸ş?9¸…ëQ¸ş?A¸…ëQ¸ş?I¸…ëQ¸ş?Qî¸Ó½~!?Y%4Œfşï?ŠUnknown
]aDevice_Recv"Size/_16(1é&1¬ú?9é&1¬ú?Aé&1¬ú?Ié&1¬ú?QûSNÜ½ ?Y˜’Nÿï?ŠUnknown
ŒbDevice_Recv"7categorical_crossentropy/weighted_loss/num_elements/_14(1+‡ÙÎ÷ó?9+‡ÙÎ÷ó?A+‡ÙÎ÷ó?I+‡ÙÎ÷ó?QÏÖ,]¾-?Yÿÿÿÿÿÿï?ŠUnknown
BcHostIDLE"IDLE1˜nƒˆùã@A˜nƒˆùã@aÈvL“£ê?iÈvL“£ê?ŠUnknown
€dHostDataset"*Iterator::Root::MapAndBatch::ParallelMapV2(€1#Ûù~jW²@9#Ûù~jWB@A#Ûù~jW²@I#Ûù~jWB@a×zòäõu¸?i#Æ»R²í?ŠUnknown
WeHostCast"Cast(€1ü©ñÒM6 @9ü©ñÒM60@Aü©ñÒM6 @Iü©ñÒM60@a¡H7û¥?i5P0¼Aï?ŠUnknown
‰fHostDataset"3Iterator::Root::MapAndBatch::ParallelMapV2::Shuffle(€1‡ÙÎw¨”@9‡ÙÎw¨$@AøSã¥›+†@IøSã¥›+@aÏ5V:-‘?i©q†‚ï?ŠUnknown
–gHostDataset"@Iterator::Root::MapAndBatch::ParallelMapV2::Shuffle::MemoryCache(€1ÙÎ÷S%ƒ@9ÙÎ÷S%@AF¶óıÔ~@IF¶óıÔ@a?crGµ„?i™r7FÍÒï?ŠUnknown
šhHostDataset"DIterator::Root::MapAndBatch::ParallelMapV2::Shuffle::MemoryCacheImpl(€1Ï÷Sã¥c`@9Ï÷Sã¥cğ?AÏ÷Sã¥c`@IÏ÷Sã¥cğ?aæì5tÛe?i†¨Sº¨èï?ŠUnknown
uiHostFlushSummaryWriter"FlushSummaryWriter(1ü©ñÒMâD@9ü©ñÒMâD@Aü©ñÒMâD@Iü©ñÒMâD@aÒÔÚK?i»-·:Ÿïï?ŠUnknown
ejHost
LogicalAnd"
LogicalAnd(1'1¬ŠA@9'1¬ŠA@A'1¬ŠA@I'1¬ŠA@aĞ-)dG?iüøúDxõï?ŠUnknown
ikHostWriteSummary"WriteSummary(1q=
×£Ğ4@9q=
×£Ğ4@Aq=
×£Ğ4@Iq=
×£Ğ4@aºfšãrÂ;?iIlW“ğøï?ŠUnknown
plHostDataset"Iterator::Root::MapAndBatch(1j¼t“„.@9j¼t“„.@Aj¼t“„.@Ij¼t“„.@aË:~Ç;Y4?i\Ğº{ûï?ŠUnknown
cmHostDataset"Iterator::Root(1øSã¥›=@9øSã¥›=@A…ëQ¸…+@I…ëQ¸…+@aĞ.İ%ÍY2?i¶uôÆıï?ŠUnknown
lnHostIteratorGetNext"IteratorGetNext(1Ï÷Sã¥Û'@9Ï÷Sã¥Û'@AÏ÷Sã¥Û'@IÏ÷Sã¥Û'@ax(ÿ[Ñ/?i>
5
Äÿï?ŠUnknown
aoHostIdentity"Identity(1{®Gázö?9{®Gázö?A{®Gázö?I{®Gázö?aÃèázåúı>i     ğ?ŠUnknown*÷r
£DeviceConv2DBackpropFilter"?gradient_tape/sequential_1/conv2d_7/Conv2D/Conv2DBackpropFilter(1Ãõ(\Õ˜@9Ãõ(\Õ˜@AÃõ(\Õ˜@IÃõ(\Õ˜@QWXgY¿ƒÅ?YWXgY¿ƒÅ?ŠUnknown
¡DeviceConv2DBackpropInput">gradient_tape/sequential_1/conv2d_7/Conv2D/Conv2DBackpropInput(1®Gáz¬’@9®Gáz¬‚@A®Gáz¬’@I®Gáz¬‚@Qƒ»÷Lt-À?Yí‰/Ó™ØÒ?ŠUnknown
vDevice_FusedConv2D"sequential_1/conv2d_7/Relu(1®Gáz+@9®Gáz+o@A®Gáz+@I®Gáz+o@QK K.»?Y JÂŞİ˜Ù?ŠUnknown
£DeviceConv2DBackpropFilter"?gradient_tape/sequential_1/conv2d_9/Conv2D/Conv2DBackpropFilter(1%•C‰y@9%•C‰i@A%•C‰y@I%•C‰i@QâÀŒ=à¦?YâsæÙ\Ü?ŠUnknown
§DeviceSoftmaxCrossEntropyWithLogits":categorical_crossentropy/softmax_cross_entropy_with_logits(1–C‹lç£x@9–C‹lç£x@A–C‹lç£x@I–C‹lç£x@Qy]B¥(Y¥?YË-ûşß?ŠUnknown
£DeviceConv2DBackpropFilter"?gradient_tape/sequential_1/conv2d_6/Conv2D/Conv2DBackpropFilter(1¬Zdãu@9¬Zdãu@A¬Zdãu@I¬Zdãu@QñŸ—FÅö¢?Yå÷Ñk³à?ŠUnknown
„DeviceReluGrad",gradient_tape/sequential_1/conv2d_8/ReluGrad(1ü©ñÒM`u@9ü©ñÒM`u@Aü©ñÒM`u@Iü©ñÒM`u@Q±û`72…¢?Y  mõ¾Ûá?ŠUnknown
„DeviceReluGrad",gradient_tape/sequential_1/conv2d_6/ReluGrad(1^ºI)t@9^ºI)t@A^ºI)t@I^ºI)t@Qoéå`}w¡?Y7ÿ{Ë6óâ?ŠUnknown
£	DeviceConv2DBackpropFilter"?gradient_tape/sequential_1/conv2d_8/Conv2D/Conv2DBackpropFilter(1Ë¡E¶ó¥s@9Ë¡E¶ó¥s@AË¡E¶ó¥s@IË¡E¶ó¥s@Q×p§jñ¡?YDv&â•ä?ŠUnknown
¡
DeviceConv2DBackpropInput">gradient_tape/sequential_1/conv2d_9/Conv2D/Conv2DBackpropInput(1fffffds@9fffffdc@Afffffds@Ifffffdc@QÌÎ&Í ?YWóChå?ŠUnknown
gDevice_Send"IteratorGetNext/_1(1Zd;ßr@9Zd;ßr@AZd;ßr@IZd;ßr@Q5Y(ÄHŸ?Y[ 6e®
æ?ŠUnknown
¡DeviceConv2DBackpropInput">gradient_tape/sequential_1/conv2d_8/Conv2D/Conv2DBackpropInput(1Ï÷Sã¥™q@9Ï÷Sã¥™a@AÏ÷Sã¥™q@IÏ÷Sã¥™a@Q B‚¦_?Yp2jb©şæ?ŠUnknown
„DeviceReluGrad",gradient_tape/sequential_1/conv2d_7/ReluGrad(1{®Gáxq@9{®Gáxq@A{®Gáxq@I{®Gáxq@Qjû$å—F?YKZ“!Şğç?ŠUnknown
vDevice_FusedConv2D"sequential_1/conv2d_9/Relu(1İ$•Ap@9İ$•Ap@Aİ$•Ap@Iİ$•Ap@QæÖ.8.+œ?YÑT“7Òè?ŠUnknown
™DeviceMaxPoolGrad">gradient_tape/sequential_1/max_pooling2d_3/MaxPool/MaxPoolGrad(1D‹lçû¥k@9D‹lçû¥k@AD‹lçû¥k@ID‹lçû¥k@QàBŞZô—?YqåFjÚ‘é?ŠUnknown
vDevice_FusedConv2D"sequential_1/conv2d_6/Relu(1çû©ñÒõh@9çû©ñÒõh@Açû©ñÒõh@Içû©ñÒõh@Q|ööV" •?Y%ş|Û>ê?ŠUnknown
vDevice_FusedConv2D"sequential_1/conv2d_8/Relu(1œÄ °rh@9œÄ °rh@AœÄ °rh@IœÄ °rh@Q?}02gÙ”?Y!¶¦åê?ŠUnknown
{DeviceMaxPool"$sequential_1/max_pooling2d_3/MaxPool(1D‹lçûù^@9D‹lçûù^@AD‹lçûù^@ID‹lçûù^@QJW÷È†ÖŠ?Ylş³Ñ Që?ŠUnknown
„DeviceReluGrad",gradient_tape/sequential_1/conv2d_9/ReluGrad(1mçû©ñ"[@9mçû©ñ"[@Amçû©ñ"[@Imçû©ñ"[@Q+€tÒ‚‡?Yÿ…¯ë?ŠUnknown
’DeviceBiasAddGrad"7gradient_tape/sequential_1/conv2d_6/BiasAdd/BiasAddGrad(1{®Gá"[@9{®Gá"[@A{®Gá"[@I{®Gá"[@QÊÓBÄ‚‡?Yg>,ì?ŠUnknown
’DeviceBiasAddGrad"7gradient_tape/sequential_1/conv2d_7/BiasAdd/BiasAddGrad(1ôıÔxéÎW@9ôıÔxéÎW@AôıÔxéÎW@IôıÔxéÎW@Q	6ÓpŸ „?Y?‹Sª™_ì?ŠUnknown
¤DeviceConv2DBackpropFilter"@gradient_tape/sequential_1/conv2d_10/Conv2D/Conv2DBackpropFilter(1\Âõ(V@9\Âõ(F@A\Âõ(V@I\Âõ(F@QŒCF')ƒ?YM¤ğNæ«ì?ŠUnknown
¤DeviceConv2DBackpropFilter"@gradient_tape/sequential_1/conv2d_11/Conv2D/Conv2DBackpropFilter(1\Âõ(V@9\Âõ(F@A\Âõ(V@I\Âõ(F@QŒCF')ƒ?Y[½ó2øì?ŠUnknown
Device_FusedConv2D"sequential_1/conv2d_10/Relu(1mçû©ñzT@9mçû©ñzD@Amçû©ñzT@Imçû©ñzD@QG˜Ÿz¾?Y¼
Ş,?í?ŠUnknown™k=:3ç?
¢DeviceConv2DBackpropInput"?gradient_tape/sequential_1/conv2d_11/Conv2D/Conv2DBackpropInput(1+‡ÙÎ÷S@9+‡ÙÎ÷C@A+‡ÙÎ÷S@I+‡ÙÎ÷C@Q‰²kêÜL?Y†Æ³Q`„í?ŠUnknown
™DeviceMaxPoolGrad">gradient_tape/sequential_1/max_pooling2d_4/MaxPool/MaxPoolGrad(1Ûù~j¼tS@9Ûù~j¼tS@AÛù~j¼tS@IÛù~j¼tS@Q$±gMÛ€?Y‹R‡ÍÇí?ŠUnknown
wDevice_FusedConv2D"sequential_1/conv2d_11/Relu(1åĞ"Ûù&Q@9åĞ"Ûù&Q@AåĞ"Ûù&Q@IåĞ"Ûù&Q@Q
õ³š«¸}?Y ó‡Ş>î?ŠUnknown
¢DeviceConv2DBackpropInput"?gradient_tape/sequential_1/conv2d_10/Conv2D/Conv2DBackpropInput(1L7‰A`åP@9L7‰A`å@@AL7‰A`åP@IL7‰A`å@@Qû·´ÿF}?Yp$ğİÌ=î?ŠUnknown
’DeviceBiasAddGrad"7gradient_tape/sequential_1/conv2d_8/BiasAdd/BiasAddGrad(1ªñÒMbH@9ªñÒMbH@AªñÒMbH@IªñÒMbH@Qí%@ YÙt?Y¼¤ğgî?ŠUnknown
{DeviceMaxPool"$sequential_1/max_pooling2d_4/MaxPool(1Zd;ßOG@9Zd;ßOG@AZd;ßOG@IZd;ßOG@Q€—…}Égt?Yë¯ë"Oî?ŠUnknown
’DeviceBiasAddGrad"7gradient_tape/sequential_1/conv2d_9/BiasAdd/BiasAddGrad(1NbX9F@9NbX9F@ANbX9F@INbX9F@Qßš6Y7s?Y!‘u¶î?ŠUnknown
™ DeviceMaxPoolGrad">gradient_tape/sequential_1/max_pooling2d_5/MaxPool/MaxPoolGrad(1şÔxé&E@9şÔxé&E@AşÔxé&E@IşÔxé&E@Qr|Ö§¡r?Y:Ká¸Ûî?ŠUnknown
¾!Device	Transpose"egradient_tape/sequential_1/conv2d_6/Conv2D/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer(1j¼t“¸>@9j¼t“¸>@Aj¼t“¸>@Ij¼t“¸>@Q·¾zkÛj?Yù¶¼Vöî?ŠUnknown
q"DeviceMatMul"sequential_1/dense_2/MatMul(1;ßO—n2@9;ßO—n2@A;ßO—n2@I;ßO—n2@Q…xÄ\ğ_?Y ÌëNï?ŠUnknown
…#DeviceReluGrad"-gradient_tape/sequential_1/conv2d_11/ReluGrad(1ü©ñÒMb0@9ü©ñÒMb0@Aü©ñÒMb0@Iü©ñÒMb0@Q"›£®àc\?YÎpÛ€ï?ŠUnknown
…$DeviceReluGrad"-gradient_tape/sequential_1/conv2d_10/ReluGrad(19´Èv¾Ÿ*@99´Èv¾Ÿ*@A9´Èv¾Ÿ*@I9´Èv¾Ÿ*@Qîä&W?YE·n	 ï?ŠUnknown
“%DeviceBiasAddGrad"8gradient_tape/sequential_1/conv2d_11/BiasAdd/BiasAddGrad(19´Èv¾Ÿ*@99´Èv¾Ÿ*@A9´Èv¾Ÿ*@I9´Èv¾Ÿ*@Qîä&W?Y¼ş’+ï?ŠUnknown
s&DeviceSoftmax"sequential_1/dense_3/Softmax(1ºI+‡&@9ºI+‡&@AºI+‡&@IºI+‡&@Q§zxª„S?Yù
:WT5ï?ŠUnknown
g'Device_Send"IteratorGetNext/_3(1j¼t“&@9j¼t“&@Aj¼t“&@Ij¼t“&@Q:ìUõS?Yïµ´äİ>ï?ŠUnknown
\(DeviceArgMax"ArgMax(1{®Gáz$@9{®Gáz$@A{®Gáz$@I{®Gáz$@Qõ@&ml¾Q?YIë½Gï?ŠUnknown
^)DeviceArgMax"ArgMax_1(1;ßO—n"@9;ßO—n"@A;ßO—n"@I;ßO—n"@Q…xÄ\ğO?Yg2¹Oï?ŠUnknown
*DeviceMatMul"+gradient_tape/sequential_1/dense_2/MatMul_1(1;ßO—n"@9;ßO—n"@A;ßO—n"@I;ßO—n"@Q…xÄ\ğO?Y…MIµWï?ŠUnknown
q+DeviceMatMul"sequential_1/dense_3/MatMul(1;ßO—n"@9;ßO—n"@A;ßO—n"@I;ßO—n"@Q…xÄ\ğO?Y£~`±_ï?ŠUnknown
“,DeviceBiasAddGrad"8gradient_tape/sequential_1/conv2d_10/BiasAdd/BiasAddGrad(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q"›£®àcL?YLªXÊfï?ŠUnknown
-DeviceMatMul")gradient_tape/sequential_1/dense_2/MatMul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q"›£®àcL?YéôÕPãmï?ŠUnknown
.DeviceMatMul")gradient_tape/sequential_1/dense_3/MatMul(1yé&1¬@9yé&1¬@Ayé&1¬@Iyé&1¬@Q¾'Ï˜d×H?Y³(ü)tï?ŠUnknown
š/DeviceResourceApplyGradientDescent".SGD/SGD/update_12/ResourceApplyGradientDescent(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJE?Y`çäkyï?ŠUnknown
0DeviceMatMul"+gradient_tape/sequential_1/dense_3/MatMul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJE?Y¦=¾~ï?ŠUnknown
{1DeviceMaxPool"$sequential_1/max_pooling2d_5/MaxPool(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJE?Yºd^X„ï?ŠUnknown
š2DeviceResourceApplyGradientDescent".SGD/SGD/update_10/ResourceApplyGradientDescent(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Qõ@&ml¾A?YJ®yó€ˆï?ŠUnknown
½3Device	Transpose"dgradient_tape/sequential_1/max_pooling2d_5/MaxPool/MaxPoolGrad-2-TransposeNHWCToNCHW-LayoutOptimizer(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Qõ@&ml¾A?YÚ÷”ğŒï?ŠUnknown
¥4Device	Transpose"Lsequential_1/max_pooling2d_5/MaxPool-0-2-TransposeNCHWToNHWC-LayoutOptimizer(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Qõ@&ml¾A?YjA°)`‘ï?ŠUnknown
—5DeviceResourceApplyGradientDescent"+SGD/SGD/update/ResourceApplyGradientDescent(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q"›£®àc<?YİÆ¥ì”ï?ŠUnknown
š6DeviceResourceApplyGradientDescent".SGD/SGD/update_14/ResourceApplyGradientDescent(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q"›£®àc<?YPêÛ!y˜ï?ŠUnknown
™7DeviceResourceApplyGradientDescent"-SGD/SGD/update_2/ResourceApplyGradientDescent(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q"›£®àc<?YÃ¾ñœï?ŠUnknown
™8DeviceResourceApplyGradientDescent"-SGD/SGD/update_6/ResourceApplyGradientDescent(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q"›£®àc<?Y6“’Ÿï?ŠUnknown
™9DeviceResourceApplyGradientDescent"-SGD/SGD/update_8/ResourceApplyGradientDescent(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q"›£®àc<?Y©g–£ï?ŠUnknown
š:DeviceResourceApplyGradientDescent".SGD/SGD/update_13/ResourceApplyGradientDescent(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q“Á®L5?Y]ˆõ+È¥ï?ŠUnknown
™;DeviceResourceApplyGradientDescent"-SGD/SGD/update_9/ResourceApplyGradientDescent(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q“Á®L5?Y©ÍÁq¨ï?ŠUnknown
m<DeviceRelu"sequential_1/dense_2/Relu(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q“Á®L5?YÅÉ¥W«ï?ŠUnknown
v=DeviceAssignAddVariableOp"AssignAddVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?Y)¶´Ä­ï?ŠUnknown
x>DeviceAssignAddVariableOp"AssignAddVariableOp_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?YsˆÆn°ï?ŠUnknown
X?DeviceCast"Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?YÊçÖn³ï?ŠUnknown
g@Device
LogicalAnd"
LogicalAnd(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?Y!GçËÀµï?ŠUnknown
~ADeviceAssignAddVariableOp"SGD/SGD/AssignAddVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?Yx¦÷(j¸ï?ŠUnknown
™BDeviceResourceApplyGradientDescent"-SGD/SGD/update_1/ResourceApplyGradientDescent(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?YÏ†»ï?ŠUnknown
šCDeviceResourceApplyGradientDescent".SGD/SGD/update_11/ResourceApplyGradientDescent(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?Y&eã¼½ï?ŠUnknown
šDDeviceResourceApplyGradientDescent".SGD/SGD/update_15/ResourceApplyGradientDescent(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?Y}Ä(@fÀï?ŠUnknown
™EDeviceResourceApplyGradientDescent"-SGD/SGD/update_3/ResourceApplyGradientDescent(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?YÔ#9Ãï?ŠUnknown
™FDeviceResourceApplyGradientDescent"-SGD/SGD/update_4/ResourceApplyGradientDescent(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?Y+ƒIú¸Åï?ŠUnknown
™GDeviceResourceApplyGradientDescent"-SGD/SGD/update_5/ResourceApplyGradientDescent(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?Y‚âYWbÈï?ŠUnknown
™HDeviceResourceApplyGradientDescent"-SGD/SGD/update_7/ResourceApplyGradientDescent(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?YÙAj´Ëï?ŠUnknown
qIDeviceCast"categorical_crossentropy/Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?Y0¡zµÍï?ŠUnknown
ŒJDeviceCast"8categorical_crossentropy/weighted_loss/num_elements/Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?Y‡ ‹n^Ğï?ŠUnknown
„KDeviceDivNoNan",categorical_crossentropy/weighted_loss/value(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?YŞ_›ËÓï?ŠUnknown
bLDeviceDivNoNan"
div_no_nan(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?Y5¿«(±Õï?ŠUnknown
dMDeviceDivNoNan"div_no_nan_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?YŒ¼…ZØï?ŠUnknown
NDeviceTile";gradient_tape/categorical_crossentropy/weighted_loss/Tile_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?Yã}ÌâÛï?ŠUnknown
ODeviceDivNoNan"Egradient_tape/categorical_crossentropy/weighted_loss/value/div_no_nan(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?Y:İÜ?­İï?ŠUnknown
‘PDeviceBiasAddGrad"6gradient_tape/sequential_1/dense_2/BiasAdd/BiasAddGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?Y‘<íœVàï?ŠUnknown
ƒQDeviceReluGrad"+gradient_tape/sequential_1/dense_2/ReluGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?Yè›ıùÿâï?ŠUnknown
‘RDeviceBiasAddGrad"6gradient_tape/sequential_1/dense_3/BiasAdd/BiasAddGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?Y?ûW©åï?ŠUnknown
sSDeviceBiasAdd"sequential_1/dense_2/BiasAdd(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@QZ´ú‚èJ5?Y–Z´Rèï?ŠUnknown
xTDeviceAssignAddVariableOp"AssignAddVariableOp_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q"›£®àc,?YĞD)òêï?ŠUnknown
xUDeviceAssignAddVariableOp"AssignAddVariableOp_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q"›£®àc,?Y
/40ßëï?ŠUnknown
xVDeviceAssignAddVariableOp"AssignAddVariableOp_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q"›£®àc,?YD?n¥íï?ŠUnknown
ZWDeviceCast"Cast_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q"›£®àc,?Y~J¬kïï?ŠUnknown
ZXDeviceCast"Cast_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q"›£®àc,?Y¸íTê1ñï?ŠUnknown
ZYDeviceEqual"Equal(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q"›£®àc,?Yò×_(øòï?ŠUnknown
VZDeviceMul"Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q"›£®àc,?Y,Âjf¾ôï?ŠUnknown
X[DeviceSum"Sum_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q"›£®àc,?Yf¬u¤„öï?ŠUnknown
}\DeviceSum"*categorical_crossentropy/weighted_loss/Sum(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q"›£®àc,?Y –€âJøï?ŠUnknown
Ÿ]DeviceMul"Lgradient_tape/categorical_crossentropy/softmax_cross_entropy_with_logits/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q"›£®àc,?YÚ€‹ úï?ŠUnknown
s^DeviceBiasAdd"sequential_1/dense_3/BiasAdd(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q"›£®àc,?Yk–^×ûï?ŠUnknown
f_Device_Recv"strided_slice/_12(1¸…ëQ¸ş?9¸…ëQ¸ş?A¸…ëQ¸ş?I¸…ëQ¸ş?Qoa¹£¢*?Yª¦À8ıï?ŠUnknown
]`Device_Recv"Size/_16(1é&1¬ú?9é&1¬ú?Aé&1¬ú?Ié&1¬ú?QŸ_*—Ÿ&?YPY12ëşï?ŠUnknown
ŒaDevice_Recv"7categorical_crossentropy/weighted_loss/num_elements/_14(1+‡ÙÎ÷ó?9+‡ÙÎ÷ó?A+‡ÙÎ÷ó?I+‡ÙÎ÷ó?Q‰²kêÜL!?Y     ğ?ŠUnknown
€bHostDataset"*Iterator::Root::MapAndBatch::ParallelMapV2(€1#Ûù~jW²@9#Ûù~jWB@A#Ûù~jW²@I#Ûù~jWB@a_ È.4@â?i_ È.4@â?ŠUnknown
WcHostCast"Cast(€1ü©ñÒM6 @9ü©ñÒM60@Aü©ñÒM6 @Iü©ñÒM60@ao…saÉ!Ğ?ic‚ßQê?ŠUnknown
‰dHostDataset"3Iterator::Root::MapAndBatch::ParallelMapV2::Shuffle(€1‡ÙÎw¨”@9‡ÙÎw¨$@AøSã¥›+†@IøSã¥›+@a¨ºØŒ¶?i(¸™z
í?ŠUnknown
–eHostDataset"@Iterator::Root::MapAndBatch::ParallelMapV2::Shuffle::MemoryCache(€1ÙÎ÷S%ƒ@9ÙÎ÷S%@AF¶óıÔ~@IF¶óıÔ@ag0é¾ò­?i.K\6òî?ŠUnknown
šfHostDataset"DIterator::Root::MapAndBatch::ParallelMapV2::Shuffle::MemoryCacheImpl(€1Ï÷Sã¥c`@9Ï÷Sã¥cğ?AÏ÷Sã¥c`@IÏ÷Sã¥cğ?aÿE-èN?i^µ‘œ­tï?ŠUnknown
ugHostFlushSummaryWriter"FlushSummaryWriter(1ü©ñÒMâD@9ü©ñÒMâD@Aü©ñÒMâD@Iü©ñÒMâD@a}ÆßÇt?i˜¯\=ï?ŠUnknown
ehHost
LogicalAnd"
LogicalAnd(1'1¬ŠA@9'1¬ŠA@A'1¬ŠA@I'1¬ŠA@a.t¹.êsq?i€"|0%Áï?ŠUnknown
iiHostWriteSummary"WriteSummary(1q=
×£Ğ4@9q=
×£Ğ4@Aq=
×£Ğ4@Iq=
×£Ğ4@aİöh%L¶d?iw‹¡|ÛÕï?ŠUnknown
pjHostDataset"Iterator::Root::MapAndBatch(1j¼t“„.@9j¼t“„.@Aj¼t“„.@Ij¼t“„.@aÙÄíy]^?ixm˜9
åï?ŠUnknown
ckHostDataset"Iterator::Root(1øSã¥›=@9øSã¥›=@A…ëQ¸…+@I…ëQ¸…+@aôÖ\¹Jb[?iãõ^»òï?ŠUnknown
llHostIteratorGetNext"IteratorGetNext(1Ï÷Sã¥Û'@9Ï÷Sã¥Û'@AÏ÷Sã¥Û'@IÏ÷Sã¥Û'@aÏPt½W?ieƒšşï?ŠUnknown
amHostIdentity"Identity(1{®Gázö?9{®Gázö?A{®Gázö?I{®Gázö?aÀšÉ'n^&?iÿÿÿÿÿÿï?ŠUnknown2Nvidia GPU (Ampere)