# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sszabo/github/CPRE587/project/hw_top/mlp_system/vivado/mlp_system/mlp_system.srcs/sources_1/bd/mlp_system_design/ip/mlp_system_design_auto_ds_0/mlp_system_design_auto_ds_0.xci
# IP: The module: 'mlp_system_design_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sszabo/github/CPRE587/project/hw_top/mlp_system/vivado/mlp_system/mlp_system.srcs/sources_1/bd/mlp_system_design/ip/mlp_system_design_auto_ds_0/mlp_system_design_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mlp_system_design_auto_ds_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/sszabo/github/CPRE587/project/hw_top/mlp_system/vivado/mlp_system/mlp_system.srcs/sources_1/bd/mlp_system_design/ip/mlp_system_design_auto_ds_0/mlp_system_design_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mlp_system_design_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/sszabo/github/CPRE587/project/hw_top/mlp_system/vivado/mlp_system/mlp_system.srcs/sources_1/bd/mlp_system_design/ip/mlp_system_design_auto_ds_0/mlp_system_design_auto_ds_0.xci
# IP: The module: 'mlp_system_design_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sszabo/github/CPRE587/project/hw_top/mlp_system/vivado/mlp_system/mlp_system.srcs/sources_1/bd/mlp_system_design/ip/mlp_system_design_auto_ds_0/mlp_system_design_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mlp_system_design_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/sszabo/github/CPRE587/project/hw_top/mlp_system/vivado/mlp_system/mlp_system.srcs/sources_1/bd/mlp_system_design/ip/mlp_system_design_auto_ds_0/mlp_system_design_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mlp_system_design_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
