# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/sszabo/github/CPRE587/project/hw_top/mlp_system/hdl/zedboard.xdc

# Block Designs: bd/mlp_system_design/mlp_system_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design || ORIG_REF_NAME==mlp_system_design} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_input_blk_mem_0/mlp_system_design_input_blk_mem_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_input_blk_mem_0 || ORIG_REF_NAME==mlp_system_design_input_blk_mem_0} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_input_bram_ctrl_0/mlp_system_design_input_bram_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_input_bram_ctrl_0 || ORIG_REF_NAME==mlp_system_design_input_bram_ctrl_0} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_inter_cont_0/mlp_system_design_inter_cont_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_inter_cont_0 || ORIG_REF_NAME==mlp_system_design_inter_cont_0} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_mlp_conv_0_0/mlp_system_design_mlp_conv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_mlp_conv_0_0 || ORIG_REF_NAME==mlp_system_design_mlp_conv_0_0} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_output_blk_mem_0/mlp_system_design_output_blk_mem_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_output_blk_mem_0 || ORIG_REF_NAME==mlp_system_design_output_blk_mem_0} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_output_bram_ctrl_0/mlp_system_design_output_bram_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_output_bram_ctrl_0 || ORIG_REF_NAME==mlp_system_design_output_bram_ctrl_0} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_xbar_0/mlp_system_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_xbar_0 || ORIG_REF_NAME==mlp_system_design_xbar_0} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_us_0/mlp_system_design_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_us_0 || ORIG_REF_NAME==mlp_system_design_auto_us_0} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_pc_5/mlp_system_design_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_pc_5 || ORIG_REF_NAME==mlp_system_design_auto_pc_5} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_us_1/mlp_system_design_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_us_1 || ORIG_REF_NAME==mlp_system_design_auto_us_1} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_us_2/mlp_system_design_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_us_2 || ORIG_REF_NAME==mlp_system_design_auto_us_2} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_ds_0/mlp_system_design_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_ds_0 || ORIG_REF_NAME==mlp_system_design_auto_ds_0} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_pc_0/mlp_system_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_pc_0 || ORIG_REF_NAME==mlp_system_design_auto_pc_0} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_ds_1/mlp_system_design_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_ds_1 || ORIG_REF_NAME==mlp_system_design_auto_ds_1} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_pc_1/mlp_system_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_pc_1 || ORIG_REF_NAME==mlp_system_design_auto_pc_1} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_pc_2/mlp_system_design_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_pc_2 || ORIG_REF_NAME==mlp_system_design_auto_pc_2} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_ds_2/mlp_system_design_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_ds_2 || ORIG_REF_NAME==mlp_system_design_auto_ds_2} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_ds_3/mlp_system_design_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_ds_3 || ORIG_REF_NAME==mlp_system_design_auto_ds_3} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_ds_4/mlp_system_design_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_ds_4 || ORIG_REF_NAME==mlp_system_design_auto_ds_4} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_ds_5/mlp_system_design_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_ds_5 || ORIG_REF_NAME==mlp_system_design_auto_ds_5} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_pc_3/mlp_system_design_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_pc_3 || ORIG_REF_NAME==mlp_system_design_auto_pc_3} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_ds_6/mlp_system_design_auto_ds_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_ds_6 || ORIG_REF_NAME==mlp_system_design_auto_ds_6} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_ds_7/mlp_system_design_auto_ds_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_ds_7 || ORIG_REF_NAME==mlp_system_design_auto_ds_7} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_auto_pc_4/mlp_system_design_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_auto_pc_4 || ORIG_REF_NAME==mlp_system_design_auto_pc_4} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_periph_intercon_0/mlp_system_design_periph_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_periph_intercon_0 || ORIG_REF_NAME==mlp_system_design_periph_intercon_0} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_processing_system_0/mlp_system_design_processing_system_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_processing_system_0 || ORIG_REF_NAME==mlp_system_design_processing_system_0} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_rst_ps_100M_0/mlp_system_design_rst_ps_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_rst_ps_100M_0 || ORIG_REF_NAME==mlp_system_design_rst_ps_100M_0} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_system_dma_0/mlp_system_design_system_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_system_dma_0 || ORIG_REF_NAME==mlp_system_design_system_dma_0} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_weight_blk_mem_0/mlp_system_design_weight_blk_mem_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_weight_blk_mem_0 || ORIG_REF_NAME==mlp_system_design_weight_blk_mem_0} -quiet] -quiet

# IP: bd/mlp_system_design/ip/mlp_system_design_weight_bram_ctrl_0/mlp_system_design_weight_bram_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mlp_system_design_weight_bram_ctrl_0 || ORIG_REF_NAME==mlp_system_design_weight_bram_ctrl_0} -quiet] -quiet

# XDC: bd/mlp_system_design/mlp_system_design_ooc.xdc
